### ISSUE TITLE
Refactoring old code

### ISSUE THREAD

**Issue by Neoneoexe** [Caleb-Cohen/Together#33]
A work in progress, managed to refactor some of the code and divide into sub folders, add node engines for specific nodejs version
 to 16.10.0

**Comment by Caleb-Cohen** [comment]
I am excited to see what concepts you come up with here! One potential concern I have is @intelagense, and I choose BuB/MVC because it's a format we've all worked work and is accessible.

Will these changes be approachable to someone with only BuB experience? What will some of these changes allow us to do that BuB/MVC do not?

**Comment by Caleb-Cohen** [comment]
Refractor feedback also mentioned in #46:

- Get engines package so we can display node version to prevent conflicts
- Add package-lock to .gitignore
- Change file management to assist in separation of concerns between frontend and backend
- Update .ENV.Example to have more proper formatting
- Consider Vite for more efficient compiling
- Consider Nest for more seamless backend communication
- Remove .gitignore folder in frontend

**Comment by Caleb-Cohen** [comment]
Going to break these into individual issues and we will be addressing them after the merge of add-event-form in less than 48 hours.
