### ISSUE TITLE
Complete Event Addition Form

### ISSUE THREAD

**Issue by Caleb-Cohen** [Caleb-Cohen/Together#35]

**Comment by Caleb-Cohen** [comment]
@MatthewBozin

**Comment by MatthewBozin** [comment]
I'll take this on!

**Comment by MatthewBozin** [comment]
### Status Update
Built entire flow from: React button press -> data handler axios POST request -> server processing the request -> creating event document in DB

AND IT WORKS! :D

find it in branch: 35-complete-event-addition-form

### Changes

Misc:
- Fixed some bugs that were preventing app from running.

Frontend:
- Created dataHandler.js in front end as a single point of interaction between frontend and backend.
- Added handleSubmit function to UserForm.js in frontend. It takes the userData object and passes it to the dataHandler, which makes an Axios POST request to the server.

Backend:
- Added Cors package and created Cors whitelist.
- Created Events route and controller.
- Created create() function in Events controller, which adds an event to the database. This is functional as of this branch! Test it by filling out the new event form and then checking your MongoDB collection.

### Packages added
Frontend:
- Axios

Backend:
- Cors
- Nodemon

### What still needs to be done
- Form success component needs to be built
- User is not required in Event model because auth isn't set up yet (React login/auth should probably be its own issue)
- "date" and "createdAt" fields in Event documents in DB are coming out pretty janky

### Availability
Gonna be around Saturday morning PST, taking all of Sunday off, will be back in action Monday

**Comment by Caleb-Cohen** [comment]
@MatthewBozin Great work! Do you want to PR what's been done now to main or wait until the other "What still needs to be done" is completed?

**Comment by MatthewBozin** [comment]
I'll PR to add-event-form so you can look it over. Probably best to get a second set of eyes on it before it hits main!

**Comment by Caleb-Cohen** [comment]
> @Caleb-Cohen I'll PR to add-event-form so you can look it over. Probably best to get a second set of eyes on it before it hits main!

Good point will do.

**Comment by JoeDravarol** [comment]
@MatthewBozin Nice work! Whenever you're free, could you screenshot or show an example of what you mean by the `date` and `createAt` fields in the Event document coming out janky?

**Comment by Caleb-Cohen** [comment]
> @MatthewBozin Nice work! Whenever you're free, could you screenshot or show an example of what you mean by the `date` and `createAt` fields in the Event document coming out janky?

I can pull that shortly. I was planning on taking a look at the branch later today.

**Comment by Caleb-Cohen** [comment]
@JoeDravarol I was able to get it running, but I had to run the server on local host 8000 and set the whitelist to 8000 otherwise I got a CORS error. Here's what the object looks like. I don't have the same concerns about date and created at being janky, just looks ISO 8601 formatting. 

<img width="317" alt="Screen Shot 2022-11-12 at 10 31 23 AM" src="https://user-images.githubusercontent.com/75268174/201484327-a32d50ec-028f-427a-b377-1051b131657e.png">

**Comment by MatthewBozin** [comment]
Great! I must just not be familiar with that format!

**Comment by MatthewBozin** [comment]
@Caleb-Cohen What things still need to be done for this issue?

**Comment by Caleb-Cohen** [comment]
> @Caleb-Cohen What things still need to be done for this issue?

Event addition is not completed, but this was a poorly worded issue as it's not definite on the tasks. I'll close it now.

Instinct is working on the front end elements and then we'll need to adjust the schema to match.
